# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cellNeighbours <- function(cell, nr, nc) {
    .Call(`_mct_cellNeighbours`, cell, nr, nc)
}

group <- function(x, nr, nc) {
    .Call(`_mct_group`, x, nr, nc)
}

